name: Hello World Pipeline
on: push
jobs:
  my-job:   
    runs-on: ubuntu-latest
    steps:
    - name: Print hello world
      run: echo "Hello World"  
    - name: Create Directory
      run : mkdir sample_dir
    - name:  List Directory
      run: ls -lrt
